# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - read:project
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: kawaiiepic
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Detroit
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: recent
          plugin_music_provider: spotify
          plugin_music_token: "f3a9d742a007498ba23855e26653c78a, d9d50d73f5bc47828a3b72ade1330641, AQDiAsG0kg9N8RNNc7_aLcseanmEjHVjd2mdg54SXhTcviUYib5EvC-RLjR9Znldnz6CqWInc1SlUIkQfi-lTimaH_xzEWLyqNVXkDz_QM8P6uiSmMye2GUVsxeGGnA6BiQ"
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME }}
